### ISSUE TITLE
Notebook explaining an RNA-seq classifier

### ISSUE THREAD

**Issue by stephenshank** [cognoma/machine-learning#4]
There are Jupyter notebooks on [acquiring](https://github.com/dhimmel/cancer-data/blob/master/1.TCGA-download.ipynb) and [cleaning](https://github.com/dhimmel/cancer-data/blob/ffe66ab26000379adcd7138b8ff39920d4692ef1/2.TCGA-process.ipynb) data from TCGA. Is there one that has a outline of the type of classifier that Cognoma will run on this data for our users, and if not, would it be much trouble to create one?

Ideally, it would continue from 1) data acquisition and 2) cleansing (done above), and go on to 3) feature extraction, 4) learning, and 5) interpretation. Perhaps I have missed some steps?

A paper of @cgreene, @dhimmel or @gwaygenomics might also suffice, but it could be nice for everyone to have some code to play around with. Thoughts?

**Comment by dhimmel** [comment]
I think a notebook would serve as a great example here.

You could use the [subsetted files available here](https://github.com/dhimmel/cancer-data/tree/process/data/subset). For example, if you wanted to fit a model for all samples, but only a subset of the genes, you can read the datasets with:

``` python
import pandas

base_url = 'https://github.com/dhimmel/cancer-data/raw/ffe66ab26000379adcd7138b8ff39920d4692ef1/data/subset/'

# Read expression data (features)
expression_df = pandas.read_table(base_url + 'expression-matrix-all-samples.tsv')

# Read mutation data (to create the outcome/status)
mutation_df = pandas.read_table(base_url + 'mutation-matrix-all-samples.tsv')
```

For the mutation data, it may be necessary to ask whether a sample has a mutation in any of the genes (because the data is so sparse).

Making this notebook sounds like a good task. I think we could even have multiple people make their own. Anyone want to give it a try?

**Comment by cgreene** [comment]
@gwaygenomics just put up an example via PR #10 . Once that gets approved we'll have an example notebook. @stephenshank: since you posted the issue, do you want to review the PR?

**Comment by stephenshank** [comment]
Would be my pleasure! I am not sure whether or not I have the privileges to assign this to myself. At first glance, it looks very nice... thanks @gwaygenomics !

**Comment by dhimmel** [comment]
Closing as #10 is now merged.

You can see the version of the notebook at time of writing [on nbviewer](http://nbviewer.jupyter.org/github/cognoma/machine-learning/blob/892c6994d0f57c671611781d1b96cbba31ee3c7e/1.TCGA-MLexample.ipynb).
