### ISSUE TITLE
Installing a Python Neo4j driver on OSX

### ISSUE THREAD

**Issue by superkostya** [cognoma/machine-learning#73]
Hi all,

I am having hard time running the "2.TCGA-MLexample.ipynb" notebook. The problem occurs at the line

`from neo4j.v1 import GraphDatabase`

I believe I have to install Neo4j, or rather py2neo, the Python library that gives access to it. When I use the recipe from anaconda.org

`conda install -c ivoflipse py2neo=1.6.4`

I get a message

```
PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels: 
  - py2neo 1.6.4*
```

Has anybody successfully installed py2neo on OSX?

**Comment by dhimmel** [comment]
Have you tried installing the conda environment for this repository? [Instructions here](https://github.com/cognoma/machine-learning/tree/1c27195c485fd623f30dbeec57808fba1c71c687#environment).

This environment [includes a line](https://github.com/cognoma/machine-learning/blob/1c27195c485fd623f30dbeec57808fba1c71c687/environment.yml#L15) to install `neo4j-driver` using `pip`. Note that `neo4j-driver` is a different package from `py2neo`. If you want `py2neo`, I'd recommending doing `pip install py2neo`, rather than installing using conda.

Thanks for playing with the cognoma codebase!

**Comment by superkostya** [comment]
Hi Daniel,
Thanks for the tip! I did forget to install the environment. I'll try it today.

As for "pip install py2neo", I generally try to avoid mixing pip and conda; in my experience, it might cause problems later down the road. In any case, installing the environment should solve my problem.

**Comment by dhimmel** [comment]
> I'll try it today.

Cool let us know how it goes.

> As for "pip install py2neo", I generally try to avoid mixing pip and conda; in my experience, it might cause problems later down the road.

My rule of thumb is that if the package is available in the default anaconda channel, I'll install it using conda. Otherwise I use pip. I haven't had too many problems with this.

**Comment by dhimmel** [comment]
@superkostya any updates? If the problem is resolved, you can go ahead and close the issue.

**Comment by superkostya** [comment]
Summary:
As I said earlier, I totally forgot to install the environment for this project (D'oh!). After I did, the issue has been resolved. The only thing I had to do is manually install "neo4j": run the command 
`pip install neo4j-driver`
after which all was right with the world. Thanks for the help. Issue closed.
